services:

  # Users Microservice ------------
  users-microservice:
    build:
      context: ./users-microservice
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./users-microservice/.env.development
    depends_on:
      - users-db
    networks:
      - users-microservice
      - shared-network
    volumes:
      - ./users-microservice:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/src/generated
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run start:dev"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3002/api/v1/status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
  users-db:
    image: postgres:16.0-alpine3.18
    env_file:
      - ./users-microservice/.env.development
    ports:
      - "6432:5432"
    networks:
      - users-microservice

  # Transactions Microservice ------------
  transactions-microservice:
    build:
      context: ./transactions-microservice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./transactions-microservice/.env.development
    depends_on:
      - transactions-db
    networks:
      - transactions-microservice
      - shared-network
    volumes:
      - ./transactions-microservice:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/src/generated
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run start:dev"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3001/api/v1/status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
  transactions-db:
    image: postgres:16.0-alpine3.18
    env_file:
      - ./transactions-microservice/.env.development
    ports:
      - "6431:5432"
    networks:
      - transactions-microservice

networks:
  users-microservice:
    driver: bridge
  transactions-microservice:
    driver: bridge
  shared-network:
    driver: bridge
