name: Automated Tests

on: pull_request

jobs:
  transactions-tests:
    name: Transactions Microservice Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: transactions-microservice
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm ci

      - run: npm test

  users-tests:
    name: Users Microservice Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: users-microservice
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm ci

      - run: npm test
